[package]
name = "frontend"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
inference = { path = "../inference" }
log = "0.4"
gloo-timers = "0.3"
bincode = "1.3.3"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-logger = "0.2"
yew = { version = "0.20.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.70"
features = [
  'AudioBuffer',
  'AudioContext',
  'AudioContextOptions',
  'AudioDestinationNode',
  'AudioNode',
  'AudioProcessingEvent',
  'BaseAudioContext',
  'Blob',
  'Document',
  'Element',
  'HtmlElement',
  'MediaDevices',
  'MediaStream',
  'MediaStreamAudioSourceNode',
  'MediaStreamConstraints',
  'MediaStreamTrack',
  'Navigator',
  'Node',
  'Window',
  'Request',
  'RequestCache',
  'RequestInit',
  'RequestMode',
  'Response',
  'Performance',
  'ScriptProcessorNode',
  'WebSocket',
  'MessageEvent',
  'ErrorEvent',
  'BinaryType',
  'console',
]
