services:
    caddy:
        image: caddy:2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - backend
            - frontend
        networks:
            - web

    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        expose:
            - "3000"
        volumes:
            - ./whisper-small:/app/whisper-small
            - ./mel_filters.safetensors:/app/mel_filters.safetensors
        networks:
            - web

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
            args:
                TRUNK_PUBLIC_API_URL: wss://api.craftvani.in/ws
        expose:
            - "80"
        depends_on:
            - backend
        networks:
            - web

networks:
    web:

volumes:
    caddy_data:
    caddy_config:
