pub const LANGUAGES: [(&str, &str); 15] = [
    ("en", "english"),
    ("hi", "hindi"),
    ("ta", "tamil"),
    ("ur", "urdu"),
    ("ml", "malayalam"),
    ("te", "telugu"),
    ("bn", "bengali"),
    ("kn", "kannada"),
    ("ne", "nepali"),
    ("mr", "marathi"),
    ("pa", "punjabi"),
    ("sd", "sindhi"),
    ("gu", "gujarati"),
    ("sa", "sanskrit"),
    ("as", "assamese"),
];
